sudo: required

services:
 - docker

language: java

jdk:
 - oraclejdk8
env:
 global:
 - COMMIT=${TRAVIS_COMMIT::8}

install: ./gradlew --version

script: ./gradlew clean release build export

after_success:
 - cd com.easyiot.heatmap.application
 - pwd
 - cp -r configuration generated/distributions/executable/
 - cd generated/distributions/executable/
 - ls
 - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
 - export REPO=daghanacay/easy-iot-heatmap
 - docker build -t $REPO:$COMMIT .
 - docker push $REPO:$COMMIT
