sudo: required

services:
 - docker

language: java

jdk:
 - oraclejdk8
env:
 global:
 - COMMIT=${TRAVIS_COMMIT::8}

install: ./gradlew --version

script: ./gradlew clean release build export

after_success:
 - cd com.easyiot.heatmap.application
 - cp -r configuration generated/distributions/executable/
 - cp -r Dockerfile generated/distributions/executable/
 - cd generated/distributions/executable/
 - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
 - export REPO=daghanacay/easy-iot-heatmap
 - docker build -t $REPO:$COMMIT .
 - docker push $REPO:$COMMIT

before_deploy:
 - rm heatmap.debug.jar
 - zip -r latest *
 - mkdir -p dpl_cd_upload
 - mv latest.zip dpl_cd_upload/latest.zip

# https://github.com/travis-ci/dpl#elastic-beanstalk
# https://docs.travis-ci.com/user/deployment
deploy:
 - provider: elasticbeanstalk
   edge: true
   skip_cleanup: true
   zip-file: 'dpl_cd_upload/latest.zip'
   app: heat-map-application # Elastic Beanstalk app name
   env: Sample-env # Elastic Beanstalk env name
   bucket_name: heat-map-s3-bucket # S3 bucket used by Elastic Beanstalk
   region: ap-southeast-2
   access_key_id: $AWS_BEANSTALK_ID
   secret_access_key: $AWS_BEANSTALK_ACCES_KEY
   on:
    repo: daghanacay/com.easyiot.application
    branch: master

after_deploy:
 - pwd
 - ls
