sudo: required

services:
 - docker

language: java

jdk:
 - oraclejdk8

install: ./gradlew --version

script: ./gradlew clean release build export

after_success:
 - cd com.easyiot.heatmap.application
 - pwd
 - cp -r configuration generated/distributions/executable/
 - cd generated/distributions/executable/
 - ls
 - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
 - export REPO=daghanacay/easy-iot-heatmap
 - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
 - docker build -t $REPO:$COMMIT .
 - docker tag $REPO:$COMMIT $REPO:$TAG
 - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
 - docker push $REPO
